name: Schema/Example Test
on: pull_request
jobs:
    Test-Examples:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - run: pip install asn1tools deepdiff
            - run: make test

    Build-PDF:
        runs-on: ubuntu-latest
        env:
          APT_PACKAGES_FILE: ${{ github.workspace }}/dependencies/apt_packages.txt
        steps:
            - uses: actions/checkout@v2
              with:
                submodules: 'true'
            - name: Install Ubuntu packages
              run: |
                sudo apt-get update
                grep -vE '^#' ${APT_PACKAGES_FILE} | xargs sudo apt-get install --yes --no-install-recommends
            - run: sudo apt install asciidoctor ruby-asciidoctor-pdf
            - run: make clean && make
